export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

//see if the user is log in
export const USER_LOG_IN = 'USER_LOG_IN';

//request for the weather data asynchronous
export const REQUEST_WEATHER_PENDING = 'REQUEST_WEATHER_PENDING'
export const REQUEST_WEATHER_SUCCESS = 'REQUEST_WEATHER_SUCCESS'
export const REQUEST_WEATHER_FAILED = 'REQUEST_WEATHER_FAILED'
export const REQUEST_WEATHER_RESET = "REQUEST_WEATHER_RESET"
//request for the fiveday forecast data 
//request for the weather data asynchronous
export const REQUEST_WEATHER_FORECAST_PENDING = 'REQUEST_WEATHER_FORECAST_PENDING'
export const REQUEST_WEATHER_FORECAST_SUCCESS = 'REQUEST_WEATHER_FORECAST_SUCCESS'
export const REQUEST_WEATHER_FORECAST_FAILED = 'REQUEST_WEATHER_FORECAST_FAILED'
export const REQUEST_WEATHER_FORECAST_RESET = 'REQUEST_WEATHER_FORECAST_RESET'

//request for the weather data asynchronous
export const REQUEST_WEATHER_AND_FORECAST_PENDING = 'REQUEST_WEATHER_AND_FORECAST_PENDING'
export const REQUEST_WEATHER_AND_FORECAST_SUCCESS = 'REQUEST_WEATHER_AND_FORECAST_SUCCESS'
export const REQUEST_WEATHER_AND_FORECAST_FAILED = 'REQUEST_WEATHER_AND_FORECAST_FAILED'
export const REQUEST_WEATHER_AND_FORECAST_RESET = 'REQUEST_WEATHER_AND_FORECAST_RESET'

//request for user information from the server
export const LOAD_USER = 'LOAD_USER'

//all the user weather location
export const USER_WEATHER_LOCATION = " USER_WEATHER_LOCATION";

//APIKEY
export const API_KEY = "640285b24dd4963e697ea5be67cf8165";